Resources:
  WeddingRSVPsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WeddingRSVP
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Name
          Value: WeddingRSVP
